<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SensorMappingProfilesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => 4,
                'sensor_id' => 8,
                'profile_code' => 'MAP-SENSOR-LEMBAB-SOILMOISTURE',
                'manufacturer' => 'Rika Sensor',
                'device_model' => 'Soil Moisture Demo',
                'communication_path' => 'RS485 Modbus RTU',
                'slave_id' => 4,
                'source_parameter' => 'Soil moisture raw register',
                'source_unit' => 'raw',
                'register_address' => '0',
                'function_code' => 'FC03',
                'value_type' => 'uint16',
                'data_length' => 1,
                'byte_order' => null,
                'scale_factor' => '0.10000000',
                'offset' => '0.00000000',
                'value_interpretation' => null,
                'canonical_parameter_id' => 12,
                'value_origin' => 'direct_measurement',
                'status' => 'active',
                'created_at' => '2026-08-11 12:02:27',
                'updated_at' => '2026-08-11 12:02:27'
            ],
            [
                'id' => 5,
                'sensor_id' => 7,
                'profile_code' => 'MAP-RIKA-CUACA-WINDDIRECTION',
                'manufacturer' => 'Rika Sensor',
                'device_model' => 'RK900-11',
                'communication_path' => 'RS485 Modbus RTU',
                'slave_id' => 1,
                'source_parameter' => 'Wind direction',
                'source_unit' => 'deg',
                'register_address' => '40002',
                'function_code' => 'FC03',
                'value_type' => 'uint16',
                'data_length' => 1,
                'byte_order' => null,
                'scale_factor' => '1.00000000',
                'offset' => '0.00000000',
                'value_interpretation' => null,
                'canonical_parameter_id' => 2,
                'value_origin' => 'direct_measurement',
                'status' => 'active',
                'created_at' => '2026-08-11 12:02:27',
                'updated_at' => '2026-08-11 12:02:27'
            ],
            [
                'id' => 6,
                'sensor_id' => 7,
                'profile_code' => 'MAP-RIKA-CUACA-WINDSPEED',
                'manufacturer' => 'Rika Sensor',
                'device_model' => 'RK900-11',
                'communication_path' => 'RS485 Modbus RTU',
                'slave_id' => 1,
                'source_parameter' => 'Wind speed',
                'source_unit' => 'm/s',
                'register_address' => '40003',
                'function_code' => 'FC03',
                'value_type' => 'float32',
                'data_length' => 2,
                'byte_order' => 'CDAB',
                'scale_factor' => '1.00000000',
                'offset' => '0.00000000',
                'value_interpretation' => null,
                'canonical_parameter_id' => 1,
                'value_origin' => 'direct_measurement',
                'status' => 'active',
                'created_at' => '2026-08-11 12:02:27',
                'updated_at' => '2026-08-11 12:02:27'
            ],
            [
                'id' => 7,
                'sensor_id' => 7,
                'profile_code' => 'MAP-RIKA-CUACA-TEMPERATURE',
                'manufacturer' => 'Rika Sensor',
                'device_model' => 'RK900-11',
                'communication_path' => 'RS485 Modbus RTU',
                'slave_id' => 1,
                'source_parameter' => 'Atmospheric temperature',
                'source_unit' => 'C',
                'register_address' => '40005',
                'function_code' => 'FC03',
                'value_type' => 'float32',
                'data_length' => 2,
                'byte_order' => 'CDAB',
                'scale_factor' => '1.00000000',
                'offset' => '0.00000000',
                'value_interpretation' => null,
                'canonical_parameter_id' => 3,
                'value_origin' => 'direct_measurement',
                'status' => 'active',
                'created_at' => '2026-08-11 12:02:27',
                'updated_at' => '2026-08-11 12:02:27'
            ],
            [
                'id' => 8,
                'sensor_id' => 7,
                'profile_code' => 'MAP-RIKA-CUACA-HUMIDITY',
                'manufacturer' => 'Rika Sensor',
                'device_model' => 'RK900-11',
                'communication_path' => 'RS485 Modbus RTU',
                'slave_id' => 1,
                'source_parameter' => 'Atmospheric humidity',
                'source_unit' => '%',
                'register_address' => '40007',
                'function_code' => 'FC03',
                'value_type' => 'float32',
                'data_length' => 2,
                'byte_order' => 'CDAB',
                'scale_factor' => '1.00000000',
                'offset' => '0.00000000',
                'value_interpretation' => null,
                'canonical_parameter_id' => 4,
                'value_origin' => 'direct_measurement',
                'status' => 'active',
                'created_at' => '2026-08-11 12:02:27',
                'updated_at' => '2026-08-11 12:02:27'
            ],
            [
                'id' => 9,
                'sensor_id' => 7,
                'profile_code' => 'MAP-RIKA-CUACA-PRESSURE',
                'manufacturer' => 'Rika Sensor',
                'device_model' => 'RK900-11',
                'communication_path' => 'RS485 Modbus RTU',
                'slave_id' => 1,
                'source_parameter' => 'Atmospheric pressure',
                'source_unit' => 'hPa',
                'register_address' => '40009',
                'function_code' => 'FC03',
                'value_type' => 'float32',
                'data_length' => 2,
                'byte_order' => 'CDAB',
                'scale_factor' => '1.00000000',
                'offset' => '0.00000000',
                'value_interpretation' => null,
                'canonical_parameter_id' => 5,
                'value_origin' => 'direct_measurement',
                'status' => 'active',
                'created_at' => '2026-08-11 12:02:27',
                'updated_at' => '2026-08-11 12:02:27'
            ],
            [
                'id' => 10,
                'sensor_id' => 7,
                'profile_code' => 'MAP-RIKA-CUACA-RAINFALL',
                'manufacturer' => 'Rika Sensor',
                'device_model' => 'RK900-11',
                'communication_path' => 'RS485 Modbus RTU',
                'slave_id' => 1,
                'source_parameter' => 'Rainfall',
                'source_unit' => 'mm',
                'register_address' => '40013',
                'function_code' => 'FC03',
                'value_type' => 'float32',
                'data_length' => 2,
                'byte_order' => 'CDAB',
                'scale_factor' => '1.00000000',
                'offset' => '0.00000000',
                'value_interpretation' => null,
                'canonical_parameter_id' => 6,
                'value_origin' => 'direct_measurement',
                'status' => 'active',
                'created_at' => '2026-08-11 12:02:27',
                'updated_at' => '2026-08-11 12:02:27'
            ],
            [
                'id' => 11,
                'sensor_id' => 7,
                'profile_code' => 'MAP-RIKA-CUACA-PM25',
                'manufacturer' => 'Rika Sensor',
                'device_model' => 'RK900-11',
                'communication_path' => 'RS485 Modbus RTU',
                'slave_id' => 1,
                'source_parameter' => 'Dust concentration (PM2.5)',
                'source_unit' => 'ug/m3',
                'register_address' => '40026',
                'function_code' => 'FC03',
                'value_type' => 'float32',
                'data_length' => 2,
                'byte_order' => 'CDAB',
                'scale_factor' => '1.00000000',
                'offset' => '0.00000000',
                'value_interpretation' => null,
                'canonical_parameter_id' => 10,
                'value_origin' => 'direct_measurement',
                'status' => 'active',
                'created_at' => '2026-08-11 12:02:27',
                'updated_at' => '2026-08-11 12:02:27'
            ],
            [
                'id' => 12,
                'sensor_id' => 7,
                'profile_code' => 'MAP-RIKA-CUACA-ILLUMINATION',
                'manufacturer' => 'Rika Sensor',
                'device_model' => 'RK900-11',
                'communication_path' => 'RS485 Modbus RTU',
                'slave_id' => 1,
                'source_parameter' => 'Illumination',
                'source_unit' => 'lux',
                'register_address' => '40030',
                'function_code' => 'FC03',
                'value_type' => 'float32',
                'data_length' => 2,
                'byte_order' => 'CDAB',
                'scale_factor' => '1.00000000',
                'offset' => '0.00000000',
                'value_interpretation' => null,
                'canonical_parameter_id' => 9,
                'value_origin' => 'direct_measurement',
                'status' => 'active',
                'created_at' => '2026-08-11 12:02:27',
                'updated_at' => '2026-08-11 12:02:27'
            ],
            [
                'id' => 13,
                'sensor_id' => 7,
                'profile_code' => 'MAP-RIKA-CUACA-IRRADIANCE',
                'manufacturer' => 'Rika Sensor',
                'device_model' => 'RK900-11',
                'communication_path' => 'RS485 Modbus RTU',
                'slave_id' => 1,
                'source_parameter' => 'Radiation',
                'source_unit' => 'W/m2',
                'register_address' => '40034',
                'function_code' => 'FC03',
                'value_type' => 'float32',
                'data_length' => 2,
                'byte_order' => 'CDAB',
                'scale_factor' => '1.00000000',
                'offset' => '0.00000000',
                'value_interpretation' => null,
                'canonical_parameter_id' => 8,
                'value_origin' => 'direct_measurement',
                'status' => 'active',
                'created_at' => '2026-08-11 12:02:27',
                'updated_at' => '2026-08-11 12:02:27'
            ],
            [
                'id' => 14,
                'sensor_id' => 7,
                'profile_code' => 'MAP-RIKA-CUACA-ALTITUDE',
                'manufacturer' => 'Rika Sensor',
                'device_model' => 'RK900-11',
                'communication_path' => 'RS485 Modbus RTU',
                'slave_id' => 1,
                'source_parameter' => 'Altitude',
                'source_unit' => 'm',
                'register_address' => '40038',
                'function_code' => 'FC03',
                'value_type' => 'float32',
                'data_length' => 2,
                'byte_order' => 'CDAB',
                'scale_factor' => '1.00000000',
                'offset' => '0.00000000',
                'value_interpretation' => null,
                'canonical_parameter_id' => 7,
                'value_origin' => 'direct_measurement',
                'status' => 'active',
                'created_at' => '2026-08-11 12:02:27',
                'updated_at' => '2026-08-11 12:02:27'
            ],
            [
                'id' => 15,
                'sensor_id' => 7,
                'profile_code' => 'MAP-RIKA-CUACA-PM10',
                'manufacturer' => 'Rika Sensor',
                'device_model' => 'RK900-11',
                'communication_path' => 'RS485 Modbus RTU',
                'slave_id' => 1,
                'source_parameter' => 'PM10',
                'source_unit' => 'ug/m3',
                'register_address' => '40048',
                'function_code' => 'FC03',
                'value_type' => 'float32',
                'data_length' => 2,
                'byte_order' => 'CDAB',
                'scale_factor' => '1.00000000',
                'offset' => '0.00000000',
                'value_interpretation' => null,
                'canonical_parameter_id' => 11,
                'value_origin' => 'direct_measurement',
                'status' => 'active',
                'created_at' => '2026-08-11 12:02:27',
                'updated_at' => '2026-08-11 12:02:27'
            ]
        ];

        foreach ($data as $row) {
            DB::table('sensor_mapping_profiles')->insertOrIgnore($row);
        }
    }
}