@extends('layouts.master')
@section('title') Canonical Trace & Replay @endsection
@section('content')
@component('components.breadcrumb') @slot('li_1') Canonical Data @endslot @slot('title') Trace & Replay @endslot @endcomponent
@if ($errors->any())<div class="alert alert-danger">{{ implode(' ', $errors->all()) }}</div>@endif
<div class="row"><div class="col-xl-5"><div class="card"><div class="card-body"><h4 class="card-title">Bidirectional Trace</h4><form method="GET"><label class="form-label">Raw Event ID</label><input name="raw_event_id" type="number" min="1" class="form-control mb-2"><button class="btn btn-outline-primary">Cari Raw</button></form><hr><form method="GET"><label class="form-label">Canonical Value ID</label><input name="canonical_value_id" type="number" min="1" class="form-control mb-2"><button class="btn btn-outline-primary">Cari Canonical</button></form>@if ($raw)<a class="d-block mt-3" href="{{ route('canonical-trace.raw', $raw) }}">Buka raw event #{{ $raw->id }}</a>@endif @if ($value)<a class="d-block mt-3" href="{{ route('canonical-trace.value', $value) }}">Buka canonical value #{{ $value->id }}</a>@endif</div></div></div>
<div class="col-xl-7"><div class="card"><div class="card-body"><h4 class="card-title">Create Bounded Replay</h4><form method="POST" action="{{ route('canonical-trace.replays.create') }}">@csrf<div class="row"><div class="col-md-6 mb-3"><label class="form-label">Exact source</label><select name="source" class="form-select">@foreach ($dataLoggers as $x)<option value="data_logger:{{ $x->id }}">Logger {{ $x->logger_code }}</option>@endforeach @foreach ($sensors as $x)<option value="sensor:{{ $x->id }}">Sensor {{ $x->sensor_code }}</option>@endforeach</select></div><div class="col-md-6 mb-3"><label class="form-label">Published mapping</label><select name="mapping_profile_version_id" class="form-select">@foreach ($versions as $v)<option value="{{ $v->id }}">{{ $v->profile->name }} v{{ $v->version }}</option>@endforeach</select></div></div><div class="row"><div class="col-md-6 mb-3"><label class="form-label">Observed from (UTC)</label><input type="datetime-local" name="observed_from" class="form-control" required></div><div class="col-md-6 mb-3"><label class="form-label">Observed to (UTC)</label><input type="datetime-local" name="observed_to" class="form-control" required></div></div><div class="row"><div class="col-md-9 mb-3"><label class="form-label">Reason</label><input name="reason" class="form-control" required></div><div class="col-md-3 mb-3"><label class="form-label">Max events</label><input name="max_events" type="number" value="10000" max="10000" min="1" class="form-control"></div></div><p class="text-muted">Maksimal 31 hari. Dry-run wajib sebelum execute.</p><button class="btn btn-primary">Buat Replay Draft</button></form></div></div></div></div>
<div class="card"><div class="card-body"><h4 class="card-title">Replay Batches</h4><div class="table-responsive"><table class="table"><thead><tr><th>Batch</th><th>Scope/range</th><th>Mapping</th><th>Status</th><th>Counts</th></tr></thead><tbody>@forelse($batches as $b)<tr><td><a href="{{ route('canonical-trace.replays.show',$b) }}"><code>{{ Str::limit($b->batch_key,12) }}</code></a></td><td>{{ $b->scope_key }}<div class="text-muted">{{ $b->observed_from }} — {{ $b->observed_to }}</div></td><td>{{ $b->version->profile->name }} v{{ $b->version->version }}</td><td><span class="badge bg-info">{{ $b->status }}</span></td><td>{{ $b->processed_count }}/{{ $b->selected_count }} · U{{ $b->unchanged_count }} C{{ $b->corrected_count }} F{{ $b->failed_count }}</td></tr>@empty<tr><td colspan="5" class="text-center text-muted">Belum ada replay.</td></tr>@endforelse</tbody></table></div></div></div>
@endsection
