@extends('layouts.master')
@section('title') Canonical Trace Detail @endsection
@section('content')
@component('components.breadcrumb') @slot('li_1') Canonical Trace @endslot @slot('title') Detail @endslot @endcomponent
@if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif @if($errors->any())<div class="alert alert-danger">{{ implode(' ',$errors->all()) }}</div>@endif
@if($raw)<div class="card"><div class="card-body"><h4>Raw Event #{{ $raw->id }}</h4><p><code>{{ $raw->logical_event_key }}</code> · SHA {{ $raw->payload_hash }} · {{ $raw->observed_at }} / {{ $raw->received_at }}</p><h5>Items</h5>@foreach($raw->items as $i)<div>#{{ $i->id }} {{ $i->item_key }} / {{ $i->source_parameter }} / {{ $i->raw_value }}</div>@endforeach<h5 class="mt-3">Canonical Results</h5>@foreach($raw->canonicalValues as $v)<a class="d-block" href="{{ route('canonical-trace.value',$v) }}">#{{ $v->id }} {{ $v->parameter?->key }} = {{ $v->value_decimal ?? $v->status }} · {{ $v->origin }} · mapping #{{ $v->mapping_profile_version_id }}</a>@endforeach</div></div>@endif
@if($value)<div class="card"><div class="card-body"><h4>Canonical Value #{{ $value->id }}</h4><table class="table"><tr><th>Parameter/value</th><td>{{ $value->parameter->key }} = <code>{{ $value->value_decimal ?? '—' }}</code> {{ $value->unit->symbol }}</td></tr><tr><th>Status/origin</th><td>{{ $value->status }} / {{ $value->quality }} / {{ $value->origin }} / {{ $value->reason }}</td></tr><tr><th>Raw</th><td><a href="{{ route('canonical-trace.raw',$value->rawEvent) }}">event #{{ $value->raw_ingestion_event_id }}</a> item #{{ $value->raw_ingestion_item_id }}</td></tr><tr><th>Mapping/run</th><td>{{ $value->mappingVersion->profile->name }} v{{ $value->mappingVersion->version }} · rule #{{ $value->mapping_rule_id }} · run #{{ $value->canonical_processing_run_id }} · {{ $value->engine_version }}/{{ $value->run_mode }}</td></tr><tr><th>Times</th><td>{{ $value->observed_at }} / {{ $value->received_at }} / {{ $value->processed_at }}</td></tr></table><h5>Stage Trace</h5><pre class="text-wrap">{{ json_encode($value->stage_trace,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES) }}</pre></div></div>@endif
@if($batch)<div class="card"><div class="card-body"><h4>Replay {{ $batch->batch_key }}</h4><p>{{ $batch->scope_key }} · {{ $batch->observed_from }} — {{ $batch->observed_to }} · {{ $batch->version->profile->name }} v{{ $batch->version->version }}</p><div class="alert alert-info">Status {{ $batch->status }} · selected {{ $batch->selected_count }} · processed {{ $batch->processed_count }} · unchanged {{ $batch->unchanged_count }} · corrected {{ $batch->corrected_count }} · failed {{ $batch->failed_count }} · skipped {{ $batch->skipped_count }}</div>@if(in_array($batch->status,['draft','dry_run']))<form method="POST" action="{{ route('canonical-trace.replays.dry-run',$batch) }}" class="d-inline">@csrf<button class="btn btn-outline-primary">Dry Run</button></form>@endif @if($batch->dry_run_at && in_array($batch->status,['dry_run','paused','failed','running']))<form method="POST" action="{{ route('canonical-trace.replays.execute',$batch) }}" class="d-inline">@csrf<button class="btn btn-primary">{{ $batch->status==='paused'?'Resume':'Execute' }}</button></form>@endif<div class="table-responsive mt-3"><table class="table table-sm"><thead><tr><th>Raw</th><th>Status</th><th>Old/New</th><th>Reason</th></tr></thead><tbody>@foreach($batch->items as $i)<tr><td><a href="{{ route('canonical-trace.raw',$i->event) }}">#{{ $i->raw_ingestion_event_id }}</a></td><td>{{ $i->status }}</td><td>{{ $i->previous_value_count }}/{{ $i->new_value_count }}</td><td>{{ $i->reason }}</td></tr>@endforeach</tbody></table></div></div></div>@endif
@endsection
