<?php

return [
    'project' => [
        'id' => 'PRJ-RESQ-001',
        'name' => 'RESQ Multi Hazard Early Warning',
        'owner' => 'RESQ Operations',
        'date' => '2026-06-15',
    ],

    'clusters' => [
        [
            'id' => 'CLS-TSU-PDG',
            'project_id' => 'PRJ-RESQ-001',
            'name' => 'Padang Tsunami Cluster',
            'hazard' => 'Tsunami',
            'province' => 'Sumatera Barat',
            'city' => 'Padang',
            'beneficiaries' => 18500,
            'status' => 'Danger',
            'monitoring_station_id' => 'MS-PDG-001',
            'warning_station_id' => 'WS-PDG-001',
        ],
        [
            'id' => 'CLS-FLD-JKT',
            'project_id' => 'PRJ-RESQ-001',
            'name' => 'Jakarta Flood Cluster',
            'hazard' => 'Flood',
            'province' => 'DKI Jakarta',
            'city' => 'Jakarta Utara',
            'beneficiaries' => 12400,
            'status' => 'Normal',
            'monitoring_station_id' => 'MS-JKT-001',
            'warning_station_id' => 'WS-JKT-001',
        ],
    ],

    'monitoring_stations' => [
        [
            'id' => 'MS-PDG-001',
            'cluster_id' => 'CLS-TSU-PDG',
            'name' => 'Padang Coastal Monitoring Station',
            'coordinate' => '-0.9200, 100.3600',
            'logger_id' => 'DL-PDG-001',
            'logger_status' => 'Active',
            'connectivity_status' => 'Online',
            'warning_station_id' => 'WS-PDG-001',
            'status' => 'Danger',
        ],
        [
            'id' => 'MS-JKT-001',
            'cluster_id' => 'CLS-FLD-JKT',
            'name' => 'Jakarta Flood Monitoring Station',
            'coordinate' => '-6.1290, 106.8100',
            'logger_id' => 'DL-JKT-001',
            'logger_status' => 'Active',
            'connectivity_status' => 'Online',
            'warning_station_id' => 'WS-JKT-001',
            'status' => 'Normal',
        ],
    ],

    'data_loggers' => [
        [
            'id' => 'DL-PDG-001',
            'monitoring_station_id' => 'MS-PDG-001',
            'serial_number' => 'DL-PDG-SN-0001',
            'logger_model' => 'RESQ-DL-MH-4G',
            'vendor' => 'RESQ Device Lab',
            'firmware_version' => 'v2.4.1',
            'device_label' => 'QR-DL-PDG-001',
            'logger_status' => 'Active',
        ],
        [
            'id' => 'DL-JKT-001',
            'monitoring_station_id' => 'MS-JKT-001',
            'serial_number' => 'DL-JKT-SN-0001',
            'logger_model' => 'RESQ-DL-FLD-4G',
            'vendor' => 'RESQ Device Lab',
            'firmware_version' => 'v2.3.8',
            'device_label' => 'QR-DL-JKT-001',
            'logger_status' => 'Active',
        ],
    ],

    'connectivity' => [
        [
            'id' => 'CONN-PDG-001',
            'logger_id' => 'DL-PDG-001',
            'communication_type' => 'Cellular',
            'protocol' => 'MQTT',
            'host_or_endpoint' => 'mqtt.resq.local',
            'port' => 1883,
            'topic_or_api_path' => 'resq/telemetry/MS-PDG-001',
            'gateway_id' => 'GW-PDG-001',
            'sim_number' => '6281100010001',
            'imei' => '860000000000001',
            'apn' => 'internet',
            'connectivity_status' => 'Online',
        ],
        [
            'id' => 'CONN-JKT-001',
            'logger_id' => 'DL-JKT-001',
            'communication_type' => 'Cellular',
            'protocol' => 'MQTT',
            'host_or_endpoint' => 'mqtt.resq.local',
            'port' => 1883,
            'topic_or_api_path' => 'resq/telemetry/MS-JKT-001',
            'gateway_id' => 'GW-JKT-001',
            'sim_number' => '6281100010002',
            'imei' => '860000000000002',
            'apn' => 'internet',
            'connectivity_status' => 'Online',
        ],
    ],

    'credentials' => [
        [
            'id' => 'CRED-PDG-001',
            'logger_id' => 'DL-PDG-001',
            'device_token' => 'tok_pdg_******',
            'mqtt_username' => 'ms_pdg_001',
            'mqtt_password_hash' => 'hash_pdg_******',
            'certificate_ref' => 'cert/MS-PDG-001.pem',
            'credential_status' => 'Active',
            'created_at' => '2026-06-15 09:00:00',
            'revoked_at' => null,
        ],
        [
            'id' => 'CRED-JKT-001',
            'logger_id' => 'DL-JKT-001',
            'device_token' => 'tok_jkt_******',
            'mqtt_username' => 'ms_jkt_001',
            'mqtt_password_hash' => 'hash_jkt_******',
            'certificate_ref' => 'cert/MS-JKT-001.pem',
            'credential_status' => 'Active',
            'created_at' => '2026-06-15 09:10:00',
            'revoked_at' => null,
        ],
    ],

    'sensors' => [
        [
            'id' => 'PS-PDG-01',
            'cluster_id' => 'CLS-TSU-PDG',
            'monitoring_station_id' => 'MS-PDG-001',
            'warning_station_id' => 'WS-PDG-001',
            'type' => 'Tsunami Tide Sensor',
            'parameter' => 'sea_level_anomaly',
            'value' => '+2.8 m',
            'threshold' => '> +1.5 m',
            'status' => 'Danger',
            'last_seen' => '2 minutes ago',
        ],
        [
            'id' => 'GB-PDG-02',
            'cluster_id' => 'CLS-TSU-PDG',
            'monitoring_station_id' => 'MS-PDG-001',
            'warning_station_id' => 'WS-PDG-001',
            'type' => 'Earthquake Vibration Sensor',
            'parameter' => 'ground_vibration',
            'value' => 'MMI VI',
            'threshold' => '>= MMI V',
            'status' => 'Danger',
            'last_seen' => '4 minutes ago',
        ],
        [
            'id' => 'TMA-JKT-01',
            'cluster_id' => 'CLS-FLD-JKT',
            'monitoring_station_id' => 'MS-JKT-001',
            'warning_station_id' => 'WS-JKT-001',
            'type' => 'Flood Water Level Sensor',
            'parameter' => 'water_level',
            'value' => '42 cm',
            'threshold' => '> 100 cm',
            'status' => 'Normal',
            'last_seen' => '1 minute ago',
        ],
    ],

    'warning_stations' => [
        [
            'id' => 'WS-PDG-001',
            'cluster_id' => 'CLS-TSU-PDG',
            'source_monitoring_station_id' => 'MS-PDG-001',
            'name' => 'Padang Public Warning Station',
            'zone_id' => 'ZONE-PDG-COAST',
            'coordinate' => '-0.9550, 100.3500',
            'controller_id' => 'WSC-PDG-001',
            'output_devices' => ['Siren', 'Audio System', 'LED Display', 'Beacon Lamp'],
            'status' => 'Danger',
            'public_warning_enabled' => true,
            'last_command' => 'send_public_warning',
            'ack_response' => 'ACK-WS-PDG-001',
        ],
        [
            'id' => 'WS-JKT-001',
            'cluster_id' => 'CLS-FLD-JKT',
            'source_monitoring_station_id' => 'MS-JKT-001',
            'name' => 'Jakarta Flood Warning Station',
            'zone_id' => 'ZONE-JKT-NORTH',
            'coordinate' => '-6.1150, 106.7900',
            'controller_id' => 'WSC-JKT-001',
            'output_devices' => ['Siren', 'Beacon Lamp'],
            'status' => 'Normal',
            'public_warning_enabled' => false,
            'last_command' => 'standby',
            'ack_response' => '-',
        ],
    ],

    'ws_controllers' => [
        [
            'id' => 'WSC-PDG-001',
            'warning_station_id' => 'WS-PDG-001',
            'controller_model' => 'RESQ-WSC-MH-01',
            'vendor' => 'RESQ Device Lab',
            'serial_number' => 'WSC-PDG-SN-0001',
            'firmware_version' => 'v1.8.3',
            'device_label' => 'QR-WSC-PDG-001',
            'controller_status' => 'Danger Ready',
        ],
        [
            'id' => 'WSC-JKT-001',
            'warning_station_id' => 'WS-JKT-001',
            'controller_model' => 'RESQ-WSC-FLD-01',
            'vendor' => 'RESQ Device Lab',
            'serial_number' => 'WSC-JKT-SN-0001',
            'firmware_version' => 'v1.7.9',
            'device_label' => 'QR-WSC-JKT-001',
            'controller_status' => 'Standby',
        ],
    ],
];
